#!/bin/sh

current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ $current_branch != "gh-pages" ]
then
    echo ""
    echo "Building for deploy on Github Page..."

    npm run build

    echo ""
    echo "Build done, deploying..."

    npm run deploy

    echo 
    echo "Deployed, pushing..."

    git checkout gh-pages
    git pull
    git push
    git checkout $current_branch

    echo
    echo "Github Page pushed!"
fi

exit 0
