language: node_js
node_js:
  - "10"
before_script:
  - npm install
script: npm run-script build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: 95da35f83e9bf7909666bc65e0370a6c9f5ac781
  keep_history: true
  on:
    branch: master