language: node_js
before_script:
  - npm install
script: npm run-script build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: a697590671bb52c5f734051d6de1e57c4acadb18
  keep_history: true
  on:
    branch: master