language: node_js
node_js:
  - "12"
  - "10"
  - "8"
before_script:
  - npm install
script: npm run-script build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  keep_history: true
  on:
    branch: master